version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment: 
        MYSQL_DATABASE: prisma-db
        MYSQL_USER: me
        MYSQL_ROOT: root
        MYSQL_PASSWORD: mememe
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./storage/dbdata:/var/lib/mysql
    ports:
        - 3306:3306